"""Initial check

Revision ID: 1d287c1678fc
Revises: e01188289aee
Create Date: 2023-10-29 15:36:51.395444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d287c1678fc'
down_revision: Union[str, None] = 'e01188289aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=True),
    sa.Column('text_message', sa.VARCHAR(length=300), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_messages')
    # ### end Alembic commands ###
